BEGIN {
D["PACKAGE_NAME"]=" \"suricata\""
D["PACKAGE_TARNAME"]=" \"suricata\""
D["PACKAGE_VERSION"]=" \"7.0.0-rc1-dev\""
D["PACKAGE_STRING"]=" \"suricata 7.0.0-rc1-dev\""
D["PACKAGE_BUGREPORT"]=" \"\""
D["PACKAGE_URL"]=" \"\""
D["PACKAGE"]=" \"suricata\""
D["VERSION"]=" \"7.0.0-rc1-dev\""
D["HAVE_STDIO_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_SYS_TIME_H"]=" 1"
D["HAVE_SYS_PARAM_H"]=" 1"
D["STDC_HEADERS"]=" 1"
D["HAVE_DLFCN_H"]=" 1"
D["LT_OBJDIR"]=" \".libs/\""
D["HAVE_STDDEF_H"]=" 1"
D["HAVE_ARPA_INET_H"]=" 1"
D["HAVE_ASSERT_H"]=" 1"
D["HAVE_CTYPE_H"]=" 1"
D["HAVE_ERRNO_H"]=" 1"
D["HAVE_FCNTL_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_GETOPT_H"]=" 1"
D["HAVE_LIMITS_H"]=" 1"
D["HAVE_NETDB_H"]=" 1"
D["HAVE_NETINET_IN_H"]=" 1"
D["HAVE_POLL_H"]=" 1"
D["HAVE_SCHED_H"]=" 1"
D["HAVE_SIGNAL_H"]=" 1"
D["HAVE_STDARG_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_STDIO_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STDBOOL_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_SYS_IOCTL_H"]=" 1"
D["HAVE_SYSLOG_H"]=" 1"
D["HAVE_SYS_PRCTL_H"]=" 1"
D["HAVE_SYS_SOCKET_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_SYS_SYSCALL_H"]=" 1"
D["HAVE_SYS_TIME_H"]=" 1"
D["HAVE_TIME_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_SYS_PARAM_H"]=" 1"
D["HAVE_SYS_IOCTL_H"]=" 1"
D["HAVE_LINUX_IF_ETHER_H"]=" 1"
D["HAVE_LINUX_IF_PACKET_H"]=" 1"
D["HAVE_LINUX_FILTER_H"]=" 1"
D["HAVE_LINUX_ETHTOOL_H"]=" 1"
D["HAVE_LINUX_SOCKIOS_H"]=" 1"
D["HAVE_GLOB_H"]=" 1"
D["HAVE_LOCALE_H"]=" 1"
D["HAVE_GRP_H"]=" 1"
D["HAVE_PWD_H"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["HAVE_FNMATCH_H"]=" 1"
D["HAVE_SYS_RESOURCE_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_UN_H"]=" 1"
D["HAVE_SYS_RANDOM_H"]=" 1"
D["HAVE_UTIME_H"]=" 1"
D["HAVE_LIBGEN_H"]=" 1"
D["HAVE_STDATOMIC_H"]=" 1"
D["HAVE_SYS_QUEUE_H"]=" 1"
D["HAVE_SYS_SOCKET_H"]=" 1"
D["HAVE_NET_IF_H"]=" 1"
D["HAVE_SYS_MMAN_H"]=" 1"
D["HAVE_LINUX_IF_ARP_H"]=" 1"
D["restrict"]=" __restrict__"
D["HAVE_STRUCT_TM_TM_ZONE"]=" 1"
D["HAVE_TM_ZONE"]=" 1"
D["HAVE_PTRDIFF_T"]=" 1"
D["HAVE__BOOL"]=" 1"
D["HAVE_STDBOOL_H"]=" 1"
D["HAVE_MALLOC"]=" 1"
D["HAVE_REALLOC"]=" 1"
D["HAVE_FORK"]=" 1"
D["HAVE_VFORK"]=" 1"
D["HAVE_ALARM"]=" 1"
D["HAVE_GETPAGESIZE"]=" 1"
D["HAVE_WORKING_VFORK"]=" 1"
D["HAVE_WORKING_FORK"]=" 1"
D["HAVE_MMAP"]=" 1"
D["HAVE_MEMMEM"]=" 1"
D["HAVE_MEMSET"]=" 1"
D["HAVE_MEMCHR"]=" 1"
D["HAVE_MEMRCHR"]=" 1"
D["HAVE_MEMMOVE"]=" 1"
D["HAVE_STRCASECMP"]=" 1"
D["HAVE_STRCHR"]=" 1"
D["HAVE_STRRCHR"]=" 1"
D["HAVE_STRDUP"]=" 1"
D["HAVE_STRNDUP"]=" 1"
D["HAVE_STRNCASECMP"]=" 1"
D["HAVE_STRTOL"]=" 1"
D["HAVE_STRTOUL"]=" 1"
D["HAVE_STRSTR"]=" 1"
D["HAVE_STRPBRK"]=" 1"
D["HAVE_STRTOULL"]=" 1"
D["HAVE_STRTOUMAX"]=" 1"
D["HAVE_STRERROR"]=" 1"
D["HAVE_GETHOSTNAME"]=" 1"
D["HAVE_INET_NTOA"]=" 1"
D["HAVE_UNAME"]=" 1"
D["HAVE_GETTIMEOFDAY"]=" 1"
D["HAVE_CLOCK_GETTIME"]=" 1"
D["HAVE_UTIME"]=" 1"
D["HAVE_STRPTIME"]=" 1"
D["HAVE_TZSET"]=" 1"
D["HAVE_LOCALTIME_R"]=" 1"
D["HAVE_SOCKET"]=" 1"
D["HAVE_SETENV"]=" 1"
D["HAVE_SELECT"]=" 1"
D["HAVE_PUTENV"]=" 1"
D["HAVE_DUP2"]=" 1"
D["HAVE_ENDGRENT"]=" 1"
D["HAVE_ENDPWENT"]=" 1"
D["HAVE_ATEXIT"]=" 1"
D["HAVE_MUNMAP"]=" 1"
D["HAVE_SETRLIMIT"]=" 1"
D["HAVE_FWRITE_UNLOCKED"]=" 1"
D["HAVE_GETRANDOM"]=" 1"
D["TLS_C11"]=" 1"
D["TLS_GNU"]=" 1"
D["HAVE_LINUX_LANDLOCK_H"]=" 1"
D["HAVE_DLFCN_H"]=" 1"
D["HAVE_PLUGINS"]=" 1"
D["UNITTESTS"]=" 1"
D["HAVE_LIBZ"]=" 1"
D["HAVE_LIBPCRE2_8"]=" 1"
D["PCRE2_CODE_UNIT_WIDTH"]=" 8"
D["PCRE2_HAVE_JIT"]=" 1"
D["HAVE_LIBYAML"]=" 1"
D["HAVE_LIBPTHREAD"]=" 1"
D["HAVE_PTHREAD_SPIN_UNLOCK"]=" 1"
D["HAVE_LIBJANSSON"]=" 1"
D["BUILD_UNIX_SOCKET"]=" 1"
D["HAVE_LIBNET"]=" 1"
D["HAVE_LIBNET11"]=" 1"
D["_DEFAULT_SOURCE"]=" 1"
D["_BSD_SOURCE"]=" 1"
D["__BSD_SOURCE"]=" 1"
D["__FAVOR_BSD"]=" 1"
D["HAVE_NET_ETHERNET_H"]=" 1"
D["HAVE_LIBNET"]=" 1"
D["HAVE_LIBNET_ICMPV6_UNREACH"]=" 1"
D["HAVE_LIBNET_CAPABILITIES"]=" 1"
D["HAVE_LIBNET_INIT_CONST"]=" 1"
D["HAVE_PCAP_H"]=" 1"
D["HAVE_PCAP_H"]=" 1"
D["HAVE_PCAP_PCAP_H"]=" 1"
D["HAVE_LIBPCAP"]=" 1"
D["HAVE_LIBPCAP"]=" 1"
D["HAVE_PCAP_SET_BUFF"]=" 1"
D["HAVE_AF_PACKET"]=" 1"
D["HAVE_PACKET_FANOUT"]=" 1"
D["HAVE_TPACKET_V3"]=" 1"
D["HAVE_HW_TIMESTAMPING"]=" 1"
D["HAVE_HTP_URI_NORMALIZE_HOOK"]=" 1"
D["HAVE_HTP_TX_GET_RESPONSE_HEADERS_RAW"]=" 1"
D["HAVE_HTP_DECODE_QUERY_INPLACE"]=" 1"
D["HAVE_HTP_CONFIG_SET_RESPONSE_DECOMPRESSION_LAYER_LIMIT"]=" 1"
D["HAVE_HTP_CONFIG_SET_LZMA_MEMLIMIT"]=" 1"
D["HAVE_HTP_CONFIG_SET_LZMA_LAYERS"]=" 1"
D["HAVE_HTP_CONFIG_SET_COMPRESSION_BOMB_LIMIT"]=" 1"
D["HAVE_HTP_CONFIG_SET_COMPRESSION_TIME_LIMIT"]=" 1"
D["HAVE_LIBCAP_NG"]=" 1"
D["HAVE_LIBCAP_NG"]=" 1"
D["HAVE_LIBMAGIC"]=" 1"
D["HAVE_MAGIC"]=" 1"
D["HAVE_LUA"]=" 1"
D["CLS"]=" 64"
D["HAVE_RUST"]=" 1"
D["REVISION"]=" 1a3129f43 2023-01-08"
D["CAPTURE_OFFLOAD_MANAGER"]=" 1"
D["CAPTURE_OFFLOAD"]=" 1"
D["CONFIG_DIR"]=" \"/etc/suricata/\""
D["DATA_DIR"]=" \"/var/lib/suricata/data\""
  for (key in D) D_is_set[key] = 1
  FS = ""
}
/^[\t ]*#[\t ]*(define|undef)[\t ]+[_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ][_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]*([\t (]|$)/ {
  line = $ 0
  split(line, arg, " ")
  if (arg[1] == "#") {
    defundef = arg[2]
    mac1 = arg[3]
  } else {
    defundef = substr(arg[1], 2)
    mac1 = arg[2]
  }
  split(mac1, mac2, "(") #)
  macro = mac2[1]
  prefix = substr(line, 1, index(line, defundef) - 1)
  if (D_is_set[macro]) {
    # Preserve the white space surrounding the "#".
    print prefix "define", macro P[macro] D[macro]
    next
  } else {
    # Replace #undef with comments.  This is necessary, for example,
    # in the case of _POSIX_SOURCE, which is predefined and required
    # on some systems where configure will not decide to define it.
    if (defundef == "undef") {
      print "/*", prefix defundef, macro, "*/"
      next
    }
  }
}
{ print }
